"""Bundled emoji dataset for mojify.

Each entry is a tuple of ``(character, name, keywords)``. ``keywords`` is a
space-separated string of extra search terms used to make searching more
forgiving than matching on the name alone.

This list is intentionally bundled inside the package so mojify works fully
offline with no external API or data file.
"""

# (character, name, keywords)
EMOJIS = [
    # ── Smileys & emotion ──────────────────────────────────────────────
    ("😀", "grinning face", "smile happy joy grin"),
    ("😃", "grinning face with big eyes", "smile happy joy"),
    ("😄", "grinning face with smiling eyes", "smile happy laugh"),
    ("😁", "beaming face with smiling eyes", "smile grin happy"),
    ("😆", "grinning squinting face", "laugh haha lol smile"),
    ("😅", "grinning face with sweat", "laugh nervous relief sweat"),
    ("🤣", "rolling on the floor laughing", "rofl lol haha laugh"),
    ("😂", "face with tears of joy", "lol laugh cry haha funny"),
    ("🙂", "slightly smiling face", "smile happy"),
    ("🙃", "upside-down face", "silly sarcasm irony"),
    ("😉", "winking face", "wink flirt joke"),
    ("😊", "smiling face with smiling eyes", "blush happy smile"),
    ("😇", "smiling face with halo", "angel innocent good"),
    ("🥰", "smiling face with hearts", "love adore crush"),
    ("😍", "smiling face with heart-eyes", "love crush like"),
    ("🤩", "star-struck", "starry eyes amazed wow excited"),
    ("😘", "face blowing a kiss", "kiss love flirt"),
    ("😗", "kissing face", "kiss"),
    ("😚", "kissing face with closed eyes", "kiss love"),
    ("😋", "face savoring food", "yum delicious tasty tongue"),
    ("😛", "face with tongue", "tongue silly playful"),
    ("😜", "winking face with tongue", "tongue wink silly crazy"),
    ("🤪", "zany face", "crazy goofy wild silly"),
    ("😝", "squinting face with tongue", "tongue silly playful"),
    ("🤑", "money-mouth face", "rich dollar cash greedy"),
    ("🤗", "hugging face", "hug embrace"),
    ("🤭", "face with hand over mouth", "oops giggle quiet"),
    ("🤫", "shushing face", "quiet shh secret silence"),
    ("🤔", "thinking face", "hmm think ponder consider"),
    ("🤐", "zipper-mouth face", "quiet secret silence"),
    ("🤨", "face with raised eyebrow", "skeptical suspicious doubt"),
    ("😐", "neutral face", "meh blank expressionless"),
    ("😑", "expressionless face", "blank meh unamused"),
    ("😶", "face without mouth", "silent speechless blank"),
    ("😏", "smirking face", "smug flirt sly"),
    ("😒", "unamused face", "meh annoyed unimpressed"),
    ("🙄", "face with rolling eyes", "annoyed whatever eyeroll"),
    ("😬", "grimacing face", "awkward nervous cringe"),
    ("🤥", "lying face", "liar pinocchio nose"),
    ("😌", "relieved face", "calm content peaceful"),
    ("😔", "pensive face", "sad s2 thoughtful down"),
    ("😪", "sleepy face", "tired sleep snot"),
    ("🤤", "drooling face", "drool hungry want"),
    ("😴", "sleeping face", "sleep zzz tired bed"),
    ("😷", "face with medical mask", "sick mask ill covid"),
    ("🤒", "face with thermometer", "sick fever ill"),
    ("🤕", "face with head-bandage", "hurt injured ouch"),
    ("🤢", "nauseated face", "sick disgust gross vomit"),
    ("🤮", "face vomiting", "sick puke throw up gross"),
    ("🤧", "sneezing face", "sick sneeze tissue cold"),
    ("🥵", "hot face", "heat sweat overheated"),
    ("🥶", "cold face", "freezing frozen blue"),
    ("🥴", "woozy face", "drunk dizzy confused tipsy"),
    ("😵", "knocked-out face", "dizzy dead ko stunned"),
    ("🤯", "exploding head", "mind blown shocked wow"),
    ("🤠", "cowboy hat face", "cowboy yeehaw hat"),
    ("🥳", "partying face", "party celebrate birthday hat"),
    ("😎", "smiling face with sunglasses", "cool sunglasses awesome"),
    ("🤓", "nerd face", "geek glasses smart"),
    ("🧐", "face with monocle", "fancy inspect curious"),
    ("😕", "confused face", "puzzled unsure"),
    ("😟", "worried face", "concerned anxious"),
    ("🙁", "slightly frowning face", "sad frown down"),
    ("☹️", "frowning face", "sad unhappy"),
    ("😮", "face with open mouth", "wow surprised shock"),
    ("😯", "hushed face", "surprised stunned silence"),
    ("😲", "astonished face", "shocked amazed wow"),
    ("😳", "flushed face", "embarrassed blush shy"),
    ("🥺", "pleading face", "puppy eyes please beg cute"),
    ("😦", "frowning face with open mouth", "shock sad"),
    ("😧", "anguished face", "shock distress"),
    ("😨", "fearful face", "scared afraid fear"),
    ("😰", "anxious face with sweat", "nervous worried sweat"),
    ("😥", "sad but relieved face", "phew disappointed"),
    ("😢", "crying face", "sad tear cry"),
    ("😭", "loudly crying face", "sob sad cry tears bawl"),
    ("😱", "face screaming in fear", "scream scared shock horror"),
    ("😖", "confounded face", "frustrated upset"),
    ("😣", "persevering face", "struggle frustrated"),
    ("😞", "disappointed face", "sad down let down"),
    ("😓", "downcast face with sweat", "sad sweat hard work"),
    ("😩", "weary face", "tired exhausted frustrated"),
    ("😫", "tired face", "exhausted fed up frustrated"),
    ("🥱", "yawning face", "tired bored sleepy"),
    ("😤", "face with steam from nose", "angry frustrated triumph proud"),
    ("😡", "pouting face", "angry mad rage red"),
    ("😠", "angry face", "mad annoyed grumpy"),
    ("🤬", "face with symbols on mouth", "swear curse angry cuss"),
    ("😈", "smiling face with horns", "devil evil mischief"),
    ("👿", "angry face with horns", "devil imp evil mad"),
    ("💀", "skull", "dead death dying lol"),
    ("☠️", "skull and crossbones", "danger poison death pirate"),
    ("💩", "pile of poo", "poop crap shit funny"),
    ("🤡", "clown face", "clown circus creepy"),
    ("👹", "ogre", "monster demon japanese"),
    ("👺", "goblin", "monster tengu japanese"),
    ("👻", "ghost", "boo halloween spooky spirit"),
    ("👽", "alien", "ufo extraterrestrial space"),
    ("👾", "alien monster", "game arcade space invader"),
    ("🤖", "robot", "bot ai machine"),
    ("😺", "grinning cat", "cat happy smile"),
    ("😸", "grinning cat with smiling eyes", "cat happy"),
    ("😻", "smiling cat with heart-eyes", "cat love"),
    ("😼", "cat with wry smile", "cat smug"),
    ("😽", "kissing cat", "cat kiss"),
    ("🙀", "weary cat", "cat shocked"),
    ("😿", "crying cat", "cat sad tear"),
    ("😾", "pouting cat", "cat angry"),

    # ── Gestures & body ────────────────────────────────────────────────
    ("👋", "waving hand", "hello hi bye wave goodbye"),
    ("🤚", "raised back of hand", "stop hand"),
    ("🖐️", "hand with fingers splayed", "stop five hand"),
    ("✋", "raised hand", "stop high five hand"),
    ("🖖", "vulcan salute", "spock star trek"),
    ("👌", "OK hand", "okay perfect good"),
    ("🤌", "pinched fingers", "italian gesture what"),
    ("🤏", "pinching hand", "small tiny little bit"),
    ("✌️", "victory hand", "peace two"),
    ("🤞", "crossed fingers", "luck hope wish"),
    ("🤟", "love-you gesture", "love rock"),
    ("🤘", "sign of the horns", "rock metal"),
    ("🤙", "call me hand", "shaka hang loose"),
    ("👈", "backhand index pointing left", "point left"),
    ("👉", "backhand index pointing right", "point right"),
    ("👆", "backhand index pointing up", "point up"),
    ("👇", "backhand index pointing down", "point down"),
    ("☝️", "index pointing up", "point up one this"),
    ("👍", "thumbs up", "yes good like approve ok"),
    ("👎", "thumbs down", "no bad dislike disapprove"),
    ("✊", "raised fist", "power protest solidarity"),
    ("👊", "oncoming fist", "punch fist bump bro"),
    ("🤛", "left-facing fist", "fist bump punch"),
    ("🤜", "right-facing fist", "fist bump punch"),
    ("👏", "clapping hands", "applause clap bravo well done"),
    ("🙌", "raising hands", "celebrate praise yay hooray"),
    ("👐", "open hands", "hug open"),
    ("🤲", "palms up together", "pray beg cup"),
    ("🤝", "handshake", "deal agreement meeting partner"),
    ("🙏", "folded hands", "pray thanks please namaste hope"),
    ("✍️", "writing hand", "write sign pen"),
    ("💅", "nail polish", "nails manicure beauty fabulous"),
    ("🤳", "selfie", "photo camera phone"),
    ("💪", "flexed biceps", "strong muscle gym workout"),
    ("🦾", "mechanical arm", "robot prosthetic strong"),
    ("🧠", "brain", "smart think mind intelligence"),
    ("👀", "eyes", "look watch see staring"),
    ("👁️", "eye", "look see watch"),
    ("👅", "tongue", "lick taste"),
    ("👄", "mouth", "lips kiss"),
    ("🦷", "tooth", "dentist teeth"),

    # ── People & roles ─────────────────────────────────────────────────
    ("👶", "baby", "infant child newborn"),
    ("🧒", "child", "kid young"),
    ("👦", "boy", "child kid male"),
    ("👧", "girl", "child kid female"),
    ("🧑", "person", "adult human"),
    ("👨", "man", "male guy adult"),
    ("👩", "woman", "female lady adult"),
    ("🧔", "person with beard", "beard man"),
    ("👴", "old man", "grandpa elderly senior"),
    ("👵", "old woman", "grandma elderly senior"),
    ("👲", "person with skullcap", "hat"),
    ("👮", "police officer", "cop law enforcement"),
    ("🕵️", "detective", "spy investigate sleuth"),
    ("💂", "guard", "soldier royal"),
    ("👷", "construction worker", "builder hardhat"),
    ("🤴", "prince", "royal king"),
    ("👸", "princess", "royal queen"),
    ("👰", "person with veil", "bride wedding"),
    ("🤵", "person in tuxedo", "groom suit wedding"),
    ("🎅", "santa claus", "christmas xmas father"),
    ("🤶", "mrs claus", "christmas xmas"),
    ("🦸", "superhero", "hero power marvel"),
    ("🦹", "supervillain", "villain bad evil"),
    ("🧙", "mage", "wizard witch magic"),
    ("🧚", "fairy", "magic wings pixie"),
    ("🧛", "vampire", "dracula blood halloween"),
    ("🧜", "merperson", "mermaid sea"),
    ("🧝", "elf", "fantasy ears"),
    ("🧟", "zombie", "undead halloween dead"),
    ("🤰", "pregnant woman", "baby expecting"),
    ("🤱", "breast-feeding", "baby nursing"),
    ("🙇", "person bowing", "sorry respect apologize"),
    ("💁", "person tipping hand", "sassy information help"),
    ("🙅", "person gesturing no", "stop forbidden no"),
    ("🙆", "person gesturing ok", "yes okay"),
    ("🙋", "person raising hand", "question volunteer me"),
    ("🤦", "person facepalming", "facepalm disbelief omg"),
    ("🤷", "person shrugging", "shrug dunno whatever idk"),
    ("💆", "person getting massage", "spa relax"),
    ("💇", "person getting haircut", "salon barber"),
    ("🚶", "person walking", "walk pedestrian"),
    ("🏃", "person running", "run jog race"),
    ("💃", "woman dancing", "dance party salsa"),
    ("🕺", "man dancing", "dance party disco"),
    ("👯", "people with bunny ears", "party dance twins"),
    ("🧘", "person in lotus position", "yoga meditate zen calm"),
    ("🛀", "person taking bath", "bath relax tub"),
    ("👪", "family", "parents kids household"),

    # ── Animals & nature ───────────────────────────────────────────────
    ("🐶", "dog face", "puppy pet animal"),
    ("🐱", "cat face", "kitten pet animal meow"),
    ("🐭", "mouse face", "rodent animal"),
    ("🐹", "hamster", "pet rodent animal"),
    ("🐰", "rabbit face", "bunny animal easter"),
    ("🦊", "fox", "animal sly"),
    ("🐻", "bear", "animal grizzly"),
    ("🐼", "panda", "animal bear china"),
    ("🐨", "koala", "animal australia"),
    ("🐯", "tiger face", "animal cat"),
    ("🦁", "lion", "animal king cat"),
    ("🐮", "cow face", "animal moo cattle"),
    ("🐷", "pig face", "animal oink pork"),
    ("🐸", "frog", "animal toad ribbit"),
    ("🐵", "monkey face", "animal ape"),
    ("🐔", "chicken", "animal hen bird"),
    ("🐧", "penguin", "animal bird cold"),
    ("🐦", "bird", "animal tweet"),
    ("🐤", "baby chick", "animal bird"),
    ("🦆", "duck", "animal bird quack"),
    ("🦅", "eagle", "animal bird"),
    ("🦉", "owl", "animal bird wise"),
    ("🦇", "bat", "animal halloween night"),
    ("🐺", "wolf", "animal howl"),
    ("🐗", "boar", "animal pig"),
    ("🐴", "horse face", "animal pony"),
    ("🦄", "unicorn", "magic fantasy horse rainbow"),
    ("🐝", "honeybee", "bee insect bug honey"),
    ("🐛", "bug", "insect caterpillar"),
    ("🦋", "butterfly", "insect pretty wings"),
    ("🐌", "snail", "slow shell"),
    ("🐞", "lady beetle", "ladybug insect bug luck"),
    ("🐜", "ant", "insect bug"),
    ("🦂", "scorpion", "animal sting venom"),
    ("🕷️", "spider", "insect bug halloween web"),
    ("🐢", "turtle", "animal slow tortoise"),
    ("🐍", "snake", "animal serpent reptile"),
    ("🦎", "lizard", "animal reptile gecko"),
    ("🐙", "octopus", "animal sea tentacles"),
    ("🦑", "squid", "animal sea"),
    ("🦀", "crab", "animal sea seafood"),
    ("🦐", "shrimp", "animal sea seafood prawn"),
    ("🐠", "tropical fish", "animal sea ocean"),
    ("🐟", "fish", "animal sea ocean"),
    ("🐬", "dolphin", "animal sea ocean"),
    ("🐳", "spouting whale", "animal sea ocean"),
    ("🐋", "whale", "animal sea ocean big"),
    ("🦈", "shark", "animal sea ocean jaws"),
    ("🐊", "crocodile", "animal alligator reptile"),
    ("🐅", "tiger", "animal cat stripes"),
    ("🐆", "leopard", "animal cat spots"),
    ("🦓", "zebra", "animal stripes"),
    ("🦍", "gorilla", "animal ape monkey"),
    ("🐘", "elephant", "animal big trunk"),
    ("🦏", "rhinoceros", "animal rhino horn"),
    ("🐪", "camel", "animal desert"),
    ("🦒", "giraffe", "animal tall neck"),
    ("🐄", "cow", "animal cattle moo"),
    ("🐖", "pig", "animal pork oink"),
    ("🐑", "ewe", "sheep animal wool"),
    ("🐐", "goat", "animal"),
    ("🦌", "deer", "animal stag buck"),
    ("🐕", "dog", "animal pet puppy"),
    ("🐩", "poodle", "dog animal pet"),
    ("🐈", "cat", "animal pet kitten"),
    ("🐓", "rooster", "animal bird cock"),
    ("🦃", "turkey", "animal bird thanksgiving"),
    ("🦚", "peacock", "animal bird feathers"),
    ("🦜", "parrot", "animal bird"),
    ("🦢", "swan", "animal bird"),
    ("🐇", "rabbit", "animal bunny pet"),
    ("🦝", "raccoon", "animal trash panda"),
    ("🦨", "skunk", "animal smell stink"),
    ("🦡", "badger", "animal"),
    ("🦥", "sloth", "animal slow lazy"),
    ("🐾", "paw prints", "animal feet tracks"),
    ("🐉", "dragon", "animal fantasy mythical"),
    ("🦕", "sauropod", "dinosaur brontosaurus"),
    ("🦖", "t-rex", "dinosaur trex"),
    ("🌵", "cactus", "plant desert succulent"),
    ("🎄", "christmas tree", "xmas holiday pine"),
    ("🌲", "evergreen tree", "pine forest plant"),
    ("🌳", "deciduous tree", "forest plant nature"),
    ("🌴", "palm tree", "beach tropical vacation"),
    ("🌱", "seedling", "plant grow sprout new"),
    ("🌿", "herb", "plant leaf nature"),
    ("☘️", "shamrock", "clover irish luck"),
    ("🍀", "four leaf clover", "luck lucky irish"),
    ("🍁", "maple leaf", "autumn fall canada"),
    ("🍂", "fallen leaf", "autumn fall"),
    ("🍃", "leaf fluttering in wind", "leaves wind nature"),
    ("🌷", "tulip", "flower spring plant"),
    ("🌹", "rose", "flower love romance"),
    ("🥀", "wilted flower", "dead rose sad"),
    ("🌻", "sunflower", "flower yellow summer"),
    ("🌼", "blossom", "flower daisy"),
    ("🌸", "cherry blossom", "flower sakura spring pink"),
    ("💐", "bouquet", "flowers gift romance"),
    ("🍄", "mushroom", "fungus toadstool"),

    # ── Food & drink ───────────────────────────────────────────────────
    ("🍏", "green apple", "fruit food healthy"),
    ("🍎", "red apple", "fruit food healthy"),
    ("🍐", "pear", "fruit food"),
    ("🍊", "tangerine", "orange fruit food citrus"),
    ("🍋", "lemon", "fruit food sour citrus"),
    ("🍌", "banana", "fruit food"),
    ("🍉", "watermelon", "fruit food summer"),
    ("🍇", "grapes", "fruit food wine"),
    ("🍓", "strawberry", "fruit food berry"),
    ("🫐", "blueberries", "fruit food berry"),
    ("🍈", "melon", "fruit food cantaloupe"),
    ("🍒", "cherries", "fruit food"),
    ("🍑", "peach", "fruit food butt"),
    ("🥭", "mango", "fruit food tropical"),
    ("🍍", "pineapple", "fruit food tropical"),
    ("🥥", "coconut", "fruit food tropical"),
    ("🥝", "kiwi fruit", "food"),
    ("🍅", "tomato", "vegetable food"),
    ("🍆", "eggplant", "vegetable food aubergine"),
    ("🥑", "avocado", "food fruit healthy"),
    ("🥦", "broccoli", "vegetable food healthy"),
    ("🥬", "leafy green", "vegetable food lettuce"),
    ("🥒", "cucumber", "vegetable food pickle"),
    ("🌶️", "hot pepper", "spicy chili food"),
    ("🌽", "ear of corn", "vegetable food maize"),
    ("🥕", "carrot", "vegetable food"),
    ("🧄", "garlic", "food clove"),
    ("🧅", "onion", "food"),
    ("🥔", "potato", "vegetable food"),
    ("🍠", "roasted sweet potato", "food yam"),
    ("🥐", "croissant", "food bread breakfast"),
    ("🍞", "bread", "food loaf toast"),
    ("🥖", "baguette", "food bread french"),
    ("🥨", "pretzel", "food snack"),
    ("🧀", "cheese", "food wedge"),
    ("🥚", "egg", "food breakfast"),
    ("🍳", "cooking", "egg fried breakfast pan"),
    ("🥞", "pancakes", "food breakfast syrup"),
    ("🧇", "waffle", "food breakfast"),
    ("🥓", "bacon", "food breakfast meat"),
    ("🍗", "poultry leg", "chicken food meat drumstick"),
    ("🍖", "meat on bone", "food meat"),
    ("🌭", "hot dog", "food sausage"),
    ("🍔", "hamburger", "food burger fast food"),
    ("🍟", "french fries", "food fast food chips"),
    ("🍕", "pizza", "food italian slice"),
    ("🥪", "sandwich", "food lunch"),
    ("🌮", "taco", "food mexican"),
    ("🌯", "burrito", "food mexican wrap"),
    ("🥙", "stuffed flatbread", "food kebab gyro"),
    ("🧆", "falafel", "food middle eastern"),
    ("🥗", "green salad", "food healthy veggie"),
    ("🍝", "spaghetti", "food pasta italian"),
    ("🍜", "steaming bowl", "ramen noodles soup food"),
    ("🍲", "pot of food", "stew soup food"),
    ("🍛", "curry rice", "food indian"),
    ("🍣", "sushi", "food japanese fish"),
    ("🍱", "bento box", "food japanese lunch"),
    ("🍤", "fried shrimp", "food tempura seafood"),
    ("🍙", "rice ball", "food japanese onigiri"),
    ("🍚", "cooked rice", "food asian"),
    ("🍘", "rice cracker", "food japanese snack"),
    ("🥟", "dumpling", "food potsticker gyoza"),
    ("🍥", "fish cake", "food japanese narutomaki"),
    ("🥠", "fortune cookie", "food chinese luck"),
    ("🍢", "oden", "food japanese skewer"),
    ("🍡", "dango", "food japanese sweet"),
    ("🍦", "soft ice cream", "food dessert cone sweet"),
    ("🍧", "shaved ice", "food dessert summer"),
    ("🍨", "ice cream", "food dessert sweet"),
    ("🍩", "doughnut", "food donut sweet"),
    ("🍪", "cookie", "food biscuit sweet"),
    ("🎂", "birthday cake", "dessert party celebrate sweet"),
    ("🍰", "shortcake", "cake dessert sweet slice"),
    ("🧁", "cupcake", "dessert sweet muffin"),
    ("🥧", "pie", "dessert food sweet"),
    ("🍫", "chocolate bar", "food sweet candy"),
    ("🍬", "candy", "food sweet sugar"),
    ("🍭", "lollipop", "food sweet candy"),
    ("🍮", "custard", "food dessert pudding flan"),
    ("🍯", "honey pot", "food sweet bee"),
    ("🍼", "baby bottle", "milk infant"),
    ("🥛", "glass of milk", "drink dairy"),
    ("☕", "hot beverage", "coffee tea drink morning"),
    ("🍵", "teacup without handle", "tea drink green matcha"),
    ("🧃", "beverage box", "juice drink"),
    ("🥤", "cup with straw", "soda drink"),
    ("🍶", "sake", "drink japanese alcohol"),
    ("🍺", "beer mug", "drink alcohol pub"),
    ("🍻", "clinking beer mugs", "cheers drink alcohol toast"),
    ("🥂", "clinking glasses", "cheers champagne toast celebrate"),
    ("🍷", "wine glass", "drink alcohol red"),
    ("🥃", "tumbler glass", "whiskey drink alcohol"),
    ("🍸", "cocktail glass", "martini drink alcohol"),
    ("🍹", "tropical drink", "cocktail vacation beach"),
    ("🍾", "bottle with popping cork", "champagne celebrate party"),
    ("🧊", "ice", "cube cold frozen"),
    ("🥢", "chopsticks", "food asian eat"),
    ("🍽️", "fork and knife with plate", "dinner eat restaurant food"),
    ("🍴", "fork and knife", "eat cutlery food"),
    ("🥄", "spoon", "eat cutlery"),

    # ── Travel & places ────────────────────────────────────────────────
    ("🚗", "automobile", "car vehicle drive"),
    ("🚕", "taxi", "cab car vehicle"),
    ("🚙", "sport utility vehicle", "suv car vehicle"),
    ("🚌", "bus", "vehicle transit"),
    ("🚎", "trolleybus", "vehicle transit"),
    ("🏎️", "racing car", "fast f1 vehicle speed"),
    ("🚓", "police car", "cop vehicle siren"),
    ("🚑", "ambulance", "emergency medical vehicle"),
    ("🚒", "fire engine", "firetruck emergency vehicle"),
    ("🚐", "minibus", "van vehicle"),
    ("🚚", "delivery truck", "vehicle shipping cargo"),
    ("🚛", "articulated lorry", "truck semi vehicle"),
    ("🚜", "tractor", "farm vehicle"),
    ("🏍️", "motorcycle", "bike vehicle"),
    ("🛵", "motor scooter", "vespa vehicle"),
    ("🚲", "bicycle", "bike cycle vehicle"),
    ("🛴", "kick scooter", "vehicle"),
    ("🚂", "locomotive", "train steam vehicle"),
    ("🚆", "train", "rail vehicle transit"),
    ("🚇", "metro", "subway underground transit"),
    ("🚊", "tram", "vehicle transit"),
    ("🚄", "high-speed train", "bullet rail vehicle"),
    ("✈️", "airplane", "flight travel plane fly"),
    ("🛫", "airplane departure", "takeoff flight travel"),
    ("🛬", "airplane arrival", "landing flight travel"),
    ("🚀", "rocket", "space launch fast startup"),
    ("🛸", "flying saucer", "ufo alien space"),
    ("🚁", "helicopter", "chopper fly vehicle"),
    ("⛵", "sailboat", "boat sea sailing"),
    ("🚤", "speedboat", "boat sea fast"),
    ("🛥️", "motor boat", "boat sea"),
    ("🚢", "ship", "boat sea cruise"),
    ("⚓", "anchor", "boat ship sea"),
    ("⛽", "fuel pump", "gas station petrol"),
    ("🚦", "vertical traffic light", "stop signal"),
    ("🚥", "horizontal traffic light", "stop signal"),
    ("🗺️", "world map", "travel geography globe"),
    ("🗿", "moai", "statue easter island stone"),
    ("🗽", "statue of liberty", "new york usa landmark"),
    ("🗼", "tokyo tower", "japan landmark"),
    ("🏰", "castle", "fortress fairytale palace"),
    ("🏯", "japanese castle", "japan fortress"),
    ("🏟️", "stadium", "sports arena"),
    ("🎡", "ferris wheel", "fair amusement park"),
    ("🎢", "roller coaster", "amusement park ride"),
    ("🎠", "carousel horse", "merry go round fair"),
    ("⛲", "fountain", "water park"),
    ("⛱️", "umbrella on ground", "beach summer parasol"),
    ("🏖️", "beach with umbrella", "vacation summer sand"),
    ("🏝️", "desert island", "tropical vacation beach"),
    ("🏔️", "snow-capped mountain", "peak nature alps"),
    ("⛰️", "mountain", "nature peak hike"),
    ("🌋", "volcano", "eruption lava mountain"),
    ("🏕️", "camping", "tent outdoors nature"),
    ("🏠", "house", "home building"),
    ("🏡", "house with garden", "home building"),
    ("🏢", "office building", "work business"),
    ("🏥", "hospital", "medical health building"),
    ("🏦", "bank", "money building finance"),
    ("🏨", "hotel", "building stay travel"),
    ("🏫", "school", "education building"),
    ("🏛️", "classical building", "museum government columns"),
    ("⛪", "church", "religion christian building"),
    ("🕌", "mosque", "religion islam building"),
    ("🕍", "synagogue", "religion jewish building"),
    ("🛕", "hindu temple", "religion building"),
    ("🌁", "foggy", "city fog mist"),
    ("🌃", "night with stars", "city night sky"),
    ("🌆", "cityscape at dusk", "city sunset skyline"),
    ("🌇", "sunset", "city dusk skyline"),
    ("🌉", "bridge at night", "city golden gate"),
    ("🌄", "sunrise over mountains", "morning nature dawn"),
    ("🌅", "sunrise", "morning dawn sun"),
    ("🏙️", "cityscape", "city skyline buildings"),

    # ── Activities, sports & objects ──────────────────────────────────
    ("⚽", "soccer ball", "football sport"),
    ("🏀", "basketball", "sport hoop"),
    ("🏈", "american football", "sport nfl"),
    ("⚾", "baseball", "sport"),
    ("🥎", "softball", "sport"),
    ("🎾", "tennis", "sport racket"),
    ("🏐", "volleyball", "sport"),
    ("🏉", "rugby football", "sport"),
    ("🎱", "pool 8 ball", "billiards sport"),
    ("🏓", "ping pong", "table tennis sport"),
    ("🏸", "badminton", "sport shuttlecock"),
    ("🥅", "goal net", "sport hockey soccer"),
    ("🏒", "ice hockey", "sport stick puck"),
    ("🏑", "field hockey", "sport stick"),
    ("🥍", "lacrosse", "sport stick"),
    ("🏏", "cricket game", "sport bat"),
    ("⛳", "flag in hole", "golf sport"),
    ("🥊", "boxing glove", "fight sport"),
    ("🥋", "martial arts uniform", "karate judo sport"),
    ("🎿", "skis", "ski snow winter sport"),
    ("⛷️", "skier", "ski snow winter sport"),
    ("🏂", "snowboarder", "snow winter sport"),
    ("🏄", "surfer", "surf wave beach sport"),
    ("🏊", "swimmer", "swim pool sport"),
    ("🚣", "rowboat", "row boat sport"),
    ("🧗", "climber", "climbing rock sport"),
    ("🚴", "cyclist", "bike cycling sport"),
    ("🏆", "trophy", "win champion award prize"),
    ("🥇", "1st place medal", "gold win first winner"),
    ("🥈", "2nd place medal", "silver second"),
    ("🥉", "3rd place medal", "bronze third"),
    ("🏅", "sports medal", "award win medal"),
    ("🎖️", "military medal", "award honor"),
    ("🎯", "bullseye", "target dart goal aim"),
    ("🎮", "video game", "controller gaming play"),
    ("🕹️", "joystick", "gaming arcade retro"),
    ("🎲", "game die", "dice roll random luck"),
    ("🎰", "slot machine", "casino gamble luck vegas"),
    ("🧩", "puzzle piece", "jigsaw solve"),
    ("♟️", "chess pawn", "chess strategy game"),
    ("🎭", "performing arts", "theater drama masks"),
    ("🎨", "artist palette", "art paint creative"),
    ("🎬", "clapper board", "movie film cinema action"),
    ("🎤", "microphone", "sing karaoke music mic"),
    ("🎧", "headphone", "music listen audio"),
    ("🎼", "musical score", "music notes sheet"),
    ("🎵", "musical note", "music song melody"),
    ("🎶", "musical notes", "music song melody"),
    ("🎹", "musical keyboard", "piano music keys"),
    ("🥁", "drum", "music beat percussion"),
    ("🎷", "saxophone", "music jazz instrument"),
    ("🎺", "trumpet", "music brass instrument"),
    ("🎸", "guitar", "music rock instrument"),
    ("🎻", "violin", "music classical instrument"),
    ("🪕", "banjo", "music instrument"),
    ("🎳", "bowling", "sport strike pins"),
    ("📱", "mobile phone", "smartphone cell call"),
    ("📲", "mobile phone with arrow", "call phone"),
    ("💻", "laptop", "computer pc work code"),
    ("⌨️", "keyboard", "type computer keys"),
    ("🖥️", "desktop computer", "pc monitor screen"),
    ("🖨️", "printer", "print paper office"),
    ("🖱️", "computer mouse", "click pc"),
    ("💽", "computer disk", "minidisc storage"),
    ("💾", "floppy disk", "save storage retro"),
    ("💿", "optical disk", "cd dvd disc"),
    ("📀", "dvd", "disc movie"),
    ("📷", "camera", "photo picture"),
    ("📸", "camera with flash", "photo picture"),
    ("📹", "video camera", "film record"),
    ("🎥", "movie camera", "film cinema record"),
    ("📺", "television", "tv screen"),
    ("📻", "radio", "music broadcast"),
    ("☎️", "telephone", "call phone landline"),
    ("📞", "telephone receiver", "call phone"),
    ("📟", "pager", "beeper retro"),
    ("📠", "fax machine", "office"),
    ("🔋", "battery", "power charge energy"),
    ("🔌", "electric plug", "power charge electricity"),
    ("💡", "light bulb", "idea bright electricity"),
    ("🔦", "flashlight", "torch light"),
    ("🕯️", "candle", "light flame fire"),
    ("🧯", "fire extinguisher", "safety emergency"),
    ("🛢️", "oil drum", "barrel fuel"),
    ("💸", "money with wings", "cash flying spend"),
    ("💵", "dollar banknote", "money cash usd"),
    ("💴", "yen banknote", "money cash japan"),
    ("💶", "euro banknote", "money cash europe"),
    ("💷", "pound banknote", "money cash uk"),
    ("💰", "money bag", "cash rich wealth"),
    ("💳", "credit card", "pay money bank"),
    ("💎", "gem stone", "diamond jewel rich precious"),
    ("⚖️", "balance scale", "justice law fair"),
    ("🔧", "wrench", "tool fix repair"),
    ("🔨", "hammer", "tool build fix"),
    ("⚒️", "hammer and pick", "tools work"),
    ("🛠️", "hammer and wrench", "tools fix build settings"),
    ("⛏️", "pick", "mine dig tool"),
    ("🔩", "nut and bolt", "screw hardware tool"),
    ("⚙️", "gear", "settings cog mechanical"),
    ("🧱", "brick", "wall build construction"),
    ("⛓️", "chains", "link bound"),
    ("🧲", "magnet", "attract magnetic"),
    ("🔫", "water pistol", "gun toy squirt"),
    ("💣", "bomb", "explosive boom danger"),
    ("🧨", "firecracker", "explosive fireworks"),
    ("🔪", "kitchen knife", "cut cooking blade"),
    ("🗡️", "dagger", "knife blade weapon"),
    ("⚔️", "crossed swords", "fight battle weapon"),
    ("🛡️", "shield", "defense protect armor"),
    ("🚬", "cigarette", "smoking tobacco"),
    ("⚰️", "coffin", "death funeral grave"),
    ("⚱️", "funeral urn", "death ashes"),
    ("🔮", "crystal ball", "fortune magic future psychic"),
    ("🧿", "nazar amulet", "evil eye protection"),
    ("📿", "prayer beads", "religion rosary beads"),
    ("💈", "barber pole", "haircut shop"),
    ("🔭", "telescope", "space astronomy stars look"),
    ("🔬", "microscope", "science lab biology"),
    ("🩺", "stethoscope", "doctor medical health"),
    ("💊", "pill", "medicine drug health"),
    ("💉", "syringe", "shot vaccine medical needle"),
    ("🩹", "adhesive bandage", "band-aid hurt heal"),
    ("🌡️", "thermometer", "temperature fever hot"),
    ("🧬", "dna", "genetics science biology"),
    ("🦠", "microbe", "germ virus bacteria"),
    ("🧪", "test tube", "science lab chemistry"),
    ("🧫", "petri dish", "science lab bacteria"),
    ("🧹", "broom", "clean sweep witch"),
    ("🧺", "basket", "laundry picnic"),
    ("🧻", "roll of paper", "toilet tissue"),
    ("🧼", "soap", "clean wash hygiene"),
    ("🧽", "sponge", "clean wash"),
    ("🪣", "bucket", "pail water"),
    ("🔑", "key", "lock unlock password"),
    ("🗝️", "old key", "lock unlock antique"),
    ("🔒", "locked", "lock secure private"),
    ("🔓", "unlocked", "lock open access"),
    ("🔐", "locked with key", "secure private"),
    ("🔏", "locked with pen", "secure sign"),
    ("📌", "pushpin", "pin note location"),
    ("📍", "round pushpin", "pin location map here"),
    ("📎", "paperclip", "attach office clip"),
    ("✂️", "scissors", "cut craft"),
    ("📏", "straight ruler", "measure draw"),
    ("📐", "triangular ruler", "measure geometry"),
    ("📦", "package", "box shipping delivery parcel"),
    ("✉️", "envelope", "mail email letter"),
    ("📧", "e-mail", "email mail message"),
    ("📨", "incoming envelope", "mail receive"),
    ("📩", "envelope with arrow", "mail send"),
    ("📬", "open mailbox with raised flag", "mail inbox"),
    ("📮", "postbox", "mail send letter"),
    ("📝", "memo", "note write pencil edit"),
    ("📄", "page facing up", "document paper file"),
    ("📃", "page with curl", "document paper"),
    ("📑", "bookmark tabs", "marker note"),
    ("📊", "bar chart", "graph data stats analytics"),
    ("📈", "chart increasing", "graph up growth profit"),
    ("📉", "chart decreasing", "graph down loss decline"),
    ("📋", "clipboard", "list notes tasks"),
    ("📅", "calendar", "date schedule event"),
    ("📆", "tear-off calendar", "date schedule"),
    ("🗓️", "spiral calendar", "date schedule planner"),
    ("📁", "file folder", "directory documents"),
    ("📂", "open file folder", "directory documents"),
    ("🗂️", "card index dividers", "organize files"),
    ("📚", "books", "library read study knowledge"),
    ("📖", "open book", "read study"),
    ("📕", "closed book", "read textbook"),
    ("📓", "notebook", "write notes"),
    ("📔", "notebook with decorative cover", "journal diary"),
    ("🔖", "bookmark", "save marker tag"),
    ("🏷️", "label", "tag price"),
    ("📰", "newspaper", "news press"),
    ("🗞️", "rolled-up newspaper", "news press"),
    ("✏️", "pencil", "write draw edit"),
    ("✒️", "black nib", "pen write fountain"),
    ("🖊️", "pen", "write"),
    ("🖋️", "fountain pen", "write sign"),
    ("🖌️", "paintbrush", "art paint draw"),
    ("🖍️", "crayon", "color draw"),
    ("🗒️", "spiral notepad", "notes write"),
    ("📜", "scroll", "document ancient paper"),
    ("🧾", "receipt", "bill invoice money"),
    ("🔍", "magnifying glass tilted left", "search find zoom look"),
    ("🔎", "magnifying glass tilted right", "search find zoom"),

    # ── Symbols & hearts ───────────────────────────────────────────────
    ("❤️", "red heart", "love like romance"),
    ("🧡", "orange heart", "love like"),
    ("💛", "yellow heart", "love like friendship"),
    ("💚", "green heart", "love like"),
    ("💙", "blue heart", "love like"),
    ("💜", "purple heart", "love like"),
    ("🖤", "black heart", "love dark"),
    ("🤍", "white heart", "love pure"),
    ("🤎", "brown heart", "love"),
    ("💔", "broken heart", "heartbreak sad breakup"),
    ("❣️", "heart exclamation", "love"),
    ("💕", "two hearts", "love like"),
    ("💞", "revolving hearts", "love"),
    ("💓", "beating heart", "love pulse"),
    ("💗", "growing heart", "love"),
    ("💖", "sparkling heart", "love sparkle"),
    ("💘", "heart with arrow", "love cupid romance"),
    ("💝", "heart with ribbon", "love gift valentine"),
    ("💟", "heart decoration", "love"),
    ("💌", "love letter", "romance valentine mail"),
    ("💋", "kiss mark", "lips lipstick love"),
    ("💯", "hundred points", "100 perfect score agree"),
    ("💢", "anger symbol", "mad angry"),
    ("💥", "collision", "boom explosion bang"),
    ("💫", "dizzy", "stars sparkle"),
    ("💦", "sweat droplets", "water splash drops"),
    ("💨", "dashing away", "fast wind run zoom"),
    ("🕳️", "hole", "void empty"),
    ("💤", "zzz", "sleep tired snore"),
    ("⭐", "star", "favorite rate night"),
    ("🌟", "glowing star", "sparkle shine"),
    ("✨", "sparkles", "shine glitter magic clean new"),
    ("⚡", "high voltage", "lightning power energy fast"),
    ("☄️", "comet", "space meteor"),
    ("🔥", "fire", "hot flame lit trending burn"),
    ("🌈", "rainbow", "pride colorful lgbtq"),
    ("☀️", "sun", "sunny weather bright hot"),
    ("🌤️", "sun behind small cloud", "weather partly cloudy"),
    ("⛅", "sun behind cloud", "weather partly cloudy"),
    ("☁️", "cloud", "weather cloudy sky"),
    ("🌧️", "cloud with rain", "weather rainy"),
    ("⛈️", "cloud with lightning and rain", "storm weather thunder"),
    ("🌩️", "cloud with lightning", "thunder storm weather"),
    ("❄️", "snowflake", "cold winter snow"),
    ("☃️", "snowman", "winter cold snow"),
    ("⛄", "snowman without snow", "winter cold"),
    ("🌊", "water wave", "ocean sea surf splash"),
    ("💧", "droplet", "water drop"),
    ("🌙", "crescent moon", "night sleep sky"),
    ("🌝", "full moon face", "night sky"),
    ("🌚", "new moon face", "night dark sky"),
    ("🌞", "sun with face", "sunny bright"),
    ("🌛", "first quarter moon face", "night sky"),
    ("🌎", "globe showing americas", "earth world planet"),
    ("🌍", "globe showing europe-africa", "earth world planet"),
    ("🌏", "globe showing asia-australia", "earth world planet"),
    ("🪐", "ringed planet", "saturn space"),
    ("🌐", "globe with meridians", "world internet web global"),
    ("✅", "check mark button", "done yes correct ok approve"),
    ("☑️", "check box with check", "done yes ticked"),
    ("✔️", "check mark", "yes done correct"),
    ("❌", "cross mark", "no wrong cancel delete x"),
    ("❎", "cross mark button", "no wrong"),
    ("➕", "plus", "add math"),
    ("➖", "minus", "subtract math"),
    ("➗", "divide", "math division"),
    ("✖️", "multiply", "math times x"),
    ("♾️", "infinity", "forever endless"),
    ("‼️", "double exclamation mark", "wow surprise"),
    ("⁉️", "exclamation question mark", "what confused"),
    ("❓", "red question mark", "what huh confused"),
    ("❔", "white question mark", "what huh"),
    ("❗", "red exclamation mark", "warning important wow"),
    ("❕", "white exclamation mark", "warning"),
    ("⚠️", "warning", "caution danger alert"),
    ("🚸", "children crossing", "caution kids"),
    ("⛔", "no entry", "stop forbidden"),
    ("🚫", "prohibited", "no forbidden ban not allowed"),
    ("💲", "heavy dollar sign", "money cash currency"),
    ("⚕️", "medical symbol", "health doctor caduceus"),
    ("♻️", "recycling symbol", "recycle green environment"),
    ("⚜️", "fleur-de-lis", "royal scout france"),
    ("🔱", "trident emblem", "poseidon weapon"),
    ("📛", "name badge", "label tag"),
    ("⭕", "hollow red circle", "circle o correct"),
    ("✳️", "eight-spoked asterisk", "star symbol"),
    ("✴️", "eight-pointed star", "star symbol"),
    ("❇️", "sparkle", "shine star"),
    ("©️", "copyright", "legal"),
    ("®️", "registered", "trademark legal"),
    ("™️", "trade mark", "brand legal"),
    ("🔔", "bell", "notification alert ring"),
    ("🔕", "bell with slash", "mute silent notification"),
    ("📣", "megaphone", "announce loud shout"),
    ("📢", "loudspeaker", "announce loud volume"),
    ("🔊", "speaker high volume", "loud sound audio"),
    ("🔇", "muted speaker", "mute silent"),
    ("🎉", "party popper", "celebrate congrats party tada"),
    ("🎊", "confetti ball", "celebrate party"),
    ("🎈", "balloon", "party celebrate birthday"),
    ("🎁", "wrapped gift", "present birthday surprise"),
    ("🎀", "ribbon", "bow gift decoration"),
    ("🎗️", "reminder ribbon", "awareness support cause"),
    ("🎏", "carp streamer", "japan koi festival"),
    ("🎐", "wind chime", "japan summer"),
    ("🎍", "pine decoration", "japan new year"),
    ("🧧", "red envelope", "money luck chinese gift"),
    ("🏮", "red paper lantern", "japan light festival"),
    ("💍", "ring", "marriage engagement wedding diamond"),
    ("👑", "crown", "king queen royal"),
    ("🎩", "top hat", "fancy magic gentleman"),
    ("🎓", "graduation cap", "school graduate degree college"),
    ("🧢", "billed cap", "hat baseball"),
    ("⛑️", "rescue worker's helmet", "safety hardhat"),
    ("💄", "lipstick", "makeup beauty cosmetics"),
    ("👓", "glasses", "eyewear nerd see"),
    ("🕶️", "sunglasses", "cool shades summer"),
    ("👔", "necktie", "formal business suit"),
    ("👕", "t-shirt", "clothes shirt casual"),
    ("👖", "jeans", "pants clothes denim"),
    ("🧥", "coat", "jacket clothes winter"),
    ("👗", "dress", "clothes fashion"),
    ("👙", "bikini", "swimsuit beach summer"),
    ("👠", "high-heeled shoe", "shoe fashion heels"),
    ("👟", "running shoe", "sneaker sport athletic"),
    ("👢", "woman's boot", "shoe fashion"),
    ("🥾", "hiking boot", "shoe outdoor"),
    ("🧦", "socks", "clothes feet"),
    ("🧤", "gloves", "clothes hands winter"),
    ("🧣", "scarf", "clothes winter neck"),
    ("👜", "handbag", "purse bag fashion"),
    ("🎒", "backpack", "bag school travel"),
    ("👛", "purse", "money bag"),
    ("👝", "clutch bag", "purse fashion"),
    ("🛍️", "shopping bags", "shop buy retail"),
    ("⌚", "watch", "time wrist clock"),
    ("⏰", "alarm clock", "time wake morning"),
    ("⏱️", "stopwatch", "timer time sport"),
    ("⏲️", "timer clock", "time countdown"),
    ("🕰️", "mantelpiece clock", "time vintage"),
    ("⌛", "hourglass done", "time wait sand"),
    ("⏳", "hourglass not done", "time wait sand loading"),

    # ── Arrows ─────────────────────────────────────────────────────────
    ("⬆️", "up arrow", "north direction"),
    ("⬇️", "down arrow", "south direction"),
    ("⬅️", "left arrow", "west direction back"),
    ("➡️", "right arrow", "east direction forward next"),
    ("↗️", "up-right arrow", "northeast direction"),
    ("↘️", "down-right arrow", "southeast direction"),
    ("↙️", "down-left arrow", "southwest direction"),
    ("↖️", "up-left arrow", "northwest direction"),
    ("↕️", "up-down arrow", "vertical direction"),
    ("↔️", "left-right arrow", "horizontal direction"),
    ("🔄", "counterclockwise arrows", "refresh reload sync repeat"),
    ("🔃", "clockwise vertical arrows", "refresh reload sync"),
    ("🔙", "back arrow", "return previous"),
    ("🔚", "end arrow", "finish"),
    ("🔛", "on arrow", "activate"),
    ("🔝", "top arrow", "up"),
    ("🔜", "soon arrow", "later"),
    ("▶️", "play button", "start video media"),
    ("⏸️", "pause button", "media stop"),
    ("⏹️", "stop button", "media"),
    ("⏺️", "record button", "media"),
    ("⏭️", "next track button", "skip media forward"),
    ("⏮️", "last track button", "previous media back"),
    ("⏩", "fast-forward button", "media speed"),
    ("⏪", "fast reverse button", "rewind media"),
    ("🔀", "shuffle tracks button", "random music"),
    ("🔁", "repeat button", "loop music"),
    ("🔂", "repeat single button", "loop music"),

    # ── Flags ──────────────────────────────────────────────────────────
    ("🏁", "chequered flag", "race finish start"),
    ("🚩", "triangular flag", "marker location warning"),
    ("🎌", "crossed flags", "japan celebrate"),
    ("🏴", "black flag", "pirate"),
    ("🏳️", "white flag", "surrender peace"),
    ("🏳️‍🌈", "rainbow flag", "pride lgbtq gay"),
    ("🏴‍☠️", "pirate flag", "skull jolly roger"),
    ("🇺🇸", "flag united states", "usa america us"),
    ("🇬🇧", "flag united kingdom", "uk britain england gb"),
    ("🇨🇦", "flag canada", "canadian"),
    ("🇮🇳", "flag india", "indian"),
    ("🇯🇵", "flag japan", "japanese"),
    ("🇩🇪", "flag germany", "german deutschland"),
    ("🇫🇷", "flag france", "french"),
    ("🇮🇹", "flag italy", "italian"),
    ("🇪🇸", "flag spain", "spanish"),
    ("🇧🇷", "flag brazil", "brazilian"),
    ("🇨🇳", "flag china", "chinese"),
    ("🇰🇷", "flag south korea", "korean"),
    ("🇲🇽", "flag mexico", "mexican"),
    ("🇦🇺", "flag australia", "australian aussie"),
    ("🇷🇺", "flag russia", "russian"),
    ("🇿🇦", "flag south africa", "african"),
    ("🇳🇱", "flag netherlands", "dutch holland"),
    ("🇸🇪", "flag sweden", "swedish"),
    ("🇨🇭", "flag switzerland", "swiss"),
    ("🇮🇪", "flag ireland", "irish"),
    ("🇳🇿", "flag new zealand", "kiwi"),
    ("🇸🇬", "flag singapore", "singaporean"),
]


def search(query, limit=None):
    """Return emoji entries matching ``query``.

    Matching is case-insensitive and ranks results so that prefix matches on
    the name come first, then other name matches, then keyword matches. An
    empty query returns the full list (optionally truncated to ``limit``).
    """
    query = query.strip().lower()
    if not query:
        results = EMOJIS
        return results[:limit] if limit else list(results)

    name_exact = []
    name_prefix = []
    name_contains = []
    keyword_contains = []
    for entry in EMOJIS:
        _char, name, keywords = entry
        name_l = name.lower()
        if name_l == query:
            name_exact.append(entry)
        elif name_l.startswith(query):
            name_prefix.append(entry)
        elif query in name_l:
            name_contains.append(entry)
        elif _keyword_match(query, keywords):
            keyword_contains.append(entry)

    results = name_exact + name_prefix + name_contains + keyword_contains
    return results[:limit] if limit else results


def _keyword_match(query, keywords):
    """True if ``query`` matches the start of any space-separated keyword.

    Anchoring at word boundaries avoids noisy substring hits (e.g. "art"
    matching "heart") while still being forgiving for partial typing.
    """
    return any(kw.startswith(query) for kw in keywords.lower().split())
